version: '3.8'

services:
  hr-policy-generator:
    build: .
    ports:
      - "8501:8501"
    environment:
      # Override these with your actual API keys
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount .env file if you want to edit it without rebuilding
      - ./.env:/app/.env:ro
    restart: unless-stopped
    mem_limit: 2g
    cpus: 1.0
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandbox
    shm_size: 2gb  # Increase shared memory for Chrome